sudo: required
language: generic

arch:
  - amd64
  - arm64  # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below

services:
  - docker

before_install:
  - docker build -t aelkikhia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aelkikhia/react-test npm run test

after_success:
  - docker build -t aelkikhia/multi-client ./client
  - docker build -t aelkikhia/multi-nginx ./nginx
  - docker build -t aelkikhia/multi-api ./api
  - docker build -t aelkikhia/multi-worker ./worker
  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push docker images
  - docker push aelkikhia/multi-client
  - docker push aelkikhia/multi-nginx
  - docker push aelkikhia/multi-api
  - docker push aelkikhia/multi-worker
